### ISSUE TITLE
Implement statistics overall and for all ethnicities

### ISSUE THREAD

**Issue by gbp** [mysociety/stop-and-search#17]
Waiting for data from @JolyonJoseph

**Comment by gbp** [comment]
From the [R package commits](https://github.com/BlackThrive/ExtractSS/commit/f7a01f0ede019f7f0a89335664dc63a9eabe85ea) looks like we will be comparing: Asian, Black, Mixed, Other, White

**Comment by lucascumsille** [comment]
The following protypes have been produced. Next step: feedback from Black Thrive

PROTOTYPE V1
Filter in the content section, probably the hardest version to miss there is ethnicity filter.
<img width="1052" alt="Screenshot 2023-08-17 at 15 52 42" src="https://github.com/mysociety/stop-and-search/assets/13790153/e26ea16c-3099-4c87-85fc-d7499af72dee">

PROTOTYPE V2
Filter on the right side and above the metrics

<img width="1052" alt="Screenshot 2023-08-17 at 15 51 35" src="https://github.com/mysociety/stop-and-search/assets/13790153/9a2285e9-29c6-445e-b56f-76946ec3ddc7">

<img width="1052" alt="Screenshot 2023-08-17 at 15 51 59" src="https://github.com/mysociety/stop-and-search/assets/13790153/3a1eea32-36e7-4565-94a2-6041d1438ddf">


PROTOTYPE V3
In the metrics section we could display a graph for each ethnicity all at once or just depending on which option has been selected by the user.

<img width="1052" alt="Screenshot 2023-08-17 at 15 47 10" src="https://github.com/mysociety/stop-and-search/assets/13790153/c1289daf-5bcb-4baa-82fa-a6ca727a3281">

<img width="1052" alt="Screenshot 2023-08-17 at 15 47 20" src="https://github.com/mysociety/stop-and-search/assets/13790153/14a5ed4d-ddef-459f-b9c5-811556010c38">

**Comment by JolyonJoseph** [comment]
Version 3 is looking like a winner to me. I have a few suggestions.

- On load we could have the Overall frequnecy and stop rate as the first piece of information. Then, below, depending on what filter is selected, the ethnicity-specific info. Below is a mockup.

![image](https://github.com/mysociety/stop-and-search/assets/86312793/7cf38977-dbbc-4d7d-bea8-848e1bc76279)

- We should tidy up some language. Possibly use instead "the Black population is x more likely". Sounds a bit better for oteh categoires, e.g., the "mixed Black" population, and the "Other population" ("Other people" sounds strange).
- Again on language, i think at hte start of the sentence we should have e.g., "In Eden, **compared to the White population** the Black population is x times more likely to be stopped and searched".
- Also see the comments in image re potentially stacking the sentences. In this case, repetition of "In Eden, compared to the White population" would be unnecessary, so maybe this text would need to be separate.

**Comment by lucascumsille** [comment]
Hey Jolyon
Thanks for the feedback.

About the stacking of the sentences, not sure the benefit of it, it seems like a lot of repetition, especially because of the size of the sentences and also considering we will be adding a lot of ethnicities. The idea of this header was to use it as something eye catching, but with the stacking I’m not sure if that will be the case anymore. Unless there is a limit with the amount of sentences that will be stacked, for examples: Will be always be Black + other ethnicity, and the filter only updates the second one? Or are you thinking of an addition, so for example if someone adds Asian, a sentence for Asian will be added and then if the users also  filter by Arab, that one will stack over the Asian, giving us a total of three sentences (Black + Arab + Asian).

If the concern is users understanding the likelihood column, at the side of each index we could include a tooltip explaining the number. Something like we did for the metrics with the question marks.


Other option would be to do the stacking, but decreasing the size of the non-selected option in the filter.

Let me know what you think if you prefer to go ahead with the stacking.

All the best

Lucas Cumsille M (he/him)

Front-end/Designer


mySociety | mysociety.org
